# Generated by Django 4.1.3 on 2022-12-12 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 18, 36, 56, 165927)),
        ),
    ]
