# Generated by Django 4.1.3 on 2022-12-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_alter_grid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 16, 1, 22, 327580, tzinfo=datetime.timezone.utc)),
        ),
    ]
