# Generated by Django 4.1.3 on 2022-12-29 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_alter_grid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
